services:
  db:
    container_name: postgres-coffeshop
    image: postgres:latest
    environment:
      POSTGRES_USER: heykalsayid
      POSTGRES_PASSWORD: admin
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports: 
      - "5332:5432"
    networks:
      - db
    restart: unless-stopped
  
networks:
  db:
    driver: bridge

volumes:
  db:
