spring.application.name=coffeeshop
spring.datasource.url=jdbc:postgresql://localhost:<your-port>/coffeeshop
spring.datasource.username=<your-username>
spring.datasource.password=<your-password>
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true
